name: Run benchmarks

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release
      - name: Run
        run: |
          OUTPUT="$(cargo run --release)"
          echo "\`\`\`
          $OUTPUT
          \`\`\`" > README.md

      - name: Git commit and push
        run: |
          git config user.email 'actions@github.com'
          git config user.name 'github-actions'
          if git commit -am ':robot: Update benchmarks'; then
            git push origin HEAD:${{ github.ref }}
          fi
