name: Build and Test

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'Cargo.*'
      - 'input/**'
  pull_request:
    paths:
      - 'src/**'
      - 'Cargo.*'
      - 'input/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    
    - name: Build
      run: cargo build
    
    - name: Run tests
      run: cargo test --verbose
